/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsuariosRouteImport } from './routes/app.usuarios'
import { Route as AppSobreRouteImport } from './routes/app.sobre'
import { Route as AppQuestionarioRouteImport } from './routes/app.questionario'
import { Route as AppHistoricoRouteImport } from './routes/app.historico'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppAlterarSenhaRouteImport } from './routes/app.alterar-senha'
import { Route as AppAlertasRouteImport } from './routes/app.alertas'
import { Route as AppAtletasIndexRouteImport } from './routes/app.atletas.index'
import { Route as AppAtletasIdRouteImport } from './routes/app.atletas.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppSobreRoute = AppSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionarioRoute = AppQuestionarioRouteImport.update({
  id: '/questionario',
  path: '/questionario',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAlterarSenhaRoute = AppAlterarSenhaRouteImport.update({
  id: '/alterar-senha',
  path: '/alterar-senha',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertasRoute = AppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppRoute,
} as any)
const AppAtletasIndexRoute = AppAtletasIndexRouteImport.update({
  id: '/atletas/',
  path: '/atletas/',
  getParentRoute: () => AppRoute,
} as any)
const AppAtletasIdRoute = AppAtletasIdRouteImport.update({
  id: '/atletas/$id',
  path: '/atletas/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/alterar-senha': typeof AppAlterarSenhaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/questionario': typeof AppQuestionarioRoute
  '/app/sobre': typeof AppSobreRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/app/atletas/$id': typeof AppAtletasIdRoute
  '/app/atletas/': typeof AppAtletasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/alterar-senha': typeof AppAlterarSenhaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/questionario': typeof AppQuestionarioRoute
  '/app/sobre': typeof AppSobreRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app': typeof AppIndexRoute
  '/app/atletas/$id': typeof AppAtletasIdRoute
  '/app/atletas': typeof AppAtletasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/alterar-senha': typeof AppAlterarSenhaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/questionario': typeof AppQuestionarioRoute
  '/app/sobre': typeof AppSobreRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/app/atletas/$id': typeof AppAtletasIdRoute
  '/app/atletas/': typeof AppAtletasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/alertas'
    | '/app/alterar-senha'
    | '/app/configuracoes'
    | '/app/historico'
    | '/app/questionario'
    | '/app/sobre'
    | '/app/usuarios'
    | '/app/'
    | '/app/atletas/$id'
    | '/app/atletas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/alertas'
    | '/app/alterar-senha'
    | '/app/configuracoes'
    | '/app/historico'
    | '/app/questionario'
    | '/app/sobre'
    | '/app/usuarios'
    | '/app'
    | '/app/atletas/$id'
    | '/app/atletas'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/alertas'
    | '/app/alterar-senha'
    | '/app/configuracoes'
    | '/app/historico'
    | '/app/questionario'
    | '/app/sobre'
    | '/app/usuarios'
    | '/app/'
    | '/app/atletas/$id'
    | '/app/atletas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sobre': {
      id: '/app/sobre'
      path: '/sobre'
      fullPath: '/app/sobre'
      preLoaderRoute: typeof AppSobreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/questionario': {
      id: '/app/questionario'
      path: '/questionario'
      fullPath: '/app/questionario'
      preLoaderRoute: typeof AppQuestionarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historico': {
      id: '/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alterar-senha': {
      id: '/app/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/app/alterar-senha'
      preLoaderRoute: typeof AppAlterarSenhaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alertas': {
      id: '/app/alertas'
      path: '/alertas'
      fullPath: '/app/alertas'
      preLoaderRoute: typeof AppAlertasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/atletas/': {
      id: '/app/atletas/'
      path: '/atletas'
      fullPath: '/app/atletas/'
      preLoaderRoute: typeof AppAtletasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/atletas/$id': {
      id: '/app/atletas/$id'
      path: '/atletas/$id'
      fullPath: '/app/atletas/$id'
      preLoaderRoute: typeof AppAtletasIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertasRoute: typeof AppAlertasRoute
  AppAlterarSenhaRoute: typeof AppAlterarSenhaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppQuestionarioRoute: typeof AppQuestionarioRoute
  AppSobreRoute: typeof AppSobreRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAtletasIdRoute: typeof AppAtletasIdRoute
  AppAtletasIndexRoute: typeof AppAtletasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertasRoute: AppAlertasRoute,
  AppAlterarSenhaRoute: AppAlterarSenhaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppQuestionarioRoute: AppQuestionarioRoute,
  AppSobreRoute: AppSobreRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
  AppAtletasIdRoute: AppAtletasIdRoute,
  AppAtletasIndexRoute: AppAtletasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
